// WebRemoteControlFrontend/src/index.tsx
import { createSignal, For, Show } from "solid-js";
import type { Accessor } from "solid-js";
import { createStore } from "solid-js/store";
import { render } from "solid-js/web";
import {
  BitratePreset,
  connectionStatus,
  EventData,
  GimbalPreset,
  NamedItem,
  ResponseData,
  SrtPriority,
  WebSocketConnection,
  ZoomPreset,
} from "./utils.ts";
import {
  GitHubLink,
  Button,
  Picker,
  Section,
  Toggle,
  Title,
  ConnectingOverlay,
} from "./components.tsx";

type StatusRow = [string, string];

const filterNames = {
  pixellate: "Pixellate",
  movie: "Movie",
  grayScale: "Gray scale",
  sepia: "Sepia",
  triple: "Triple",
  twin: "Twin",
  fourThree: "4:3",
  crt: "CRT",
  pinch: "Pinch",
  whirlpool: "Whirlpool",
  poll: "Poll",
  blurFaces: "Blur faces",
  privacy: "Blur background",
  beauty: "Beauty",
  moblinInMouth: "Moblin in mouth",
  cameraMan: "Camera man",
};

const allFilterKeys = [
  "pixellate",
  "movie",
  "grayScale",
  "sepia",
  "triple",
  "twin",
  "fourThree",
  "crt",
  "pinch",
  "whirlpool",
  "poll",
  "blurFaces",
  "privacy",
  "beauty",
  "moblinInMouth",
  "cameraMan",
];

const statusKeyToName = {
  camera: "Camera",
  chat: "Chat",
  mic: "Mic",
  stream: "Stream",
  zoom: "Zoom",
  obs: "OBS",
  events: "Events",
  viewers: "Viewers",
  audioLevel: "Audio",
  location: "Location",
  moblink: "Moblink",
  remoteControl: "Remote control",
  rtmpServer: "RTMP/SRT(LA) servers",
  gameController: "Game controller",
  bitrate: "Bitrate",
  uptime: "Uptime",
  srtla: "Bonding",
  srtlaRtts: "Bonding RTT:s",
  recording: "Recording",
  browserWidgets: "Browser widgets",
  djiDevices: "DJI devices",
};

function formatBytesPerSecond(bps: number): string {
  if (bps >= 1000000) return (bps / 1000000).toFixed(1) + " Mbps";
  if (bps >= 1000) return (bps / 1000).toFixed(0) + " Kbps";
  return bps + " bps";
}

interface StatusTableProps {
  rows: Accessor<StatusRow[]>;
}

function StatusTable({ rows }: StatusTableProps) {
  return (
    <div class="overflow-x-auto">
      <table class="w-full text-sm text-left text-zinc-300 table-auto">
        <tbody>
          <For each={rows()}>
            {([name, value]) => (
              <tr class="border-b border-zinc-800">
                <td class="py-1.5 pr-4 text-zinc-200 font-medium whitespace-nowrap">{name}</td>
                <td class="py-1.5 text-zinc-200" innerHTML={value} />
              </tr>
            )}
          </For>
        </tbody>
      </table>
    </div>
  );
}

function App() {
  const [status, setStatus] = createSignal<string>(connectionStatus.connecting);
  const [generalRows, setGeneralRows] = createSignal<StatusRow[]>([]);
  const [topLeftRows, setTopLeftRows] = createSignal<StatusRow[]>([]);
  const [topRightRows, setTopRightRows] = createSignal<StatusRow[]>([]);
  const [showControl, setShowControl] = createSignal(false);
  const [showSrt, setShowSrt] = createSignal(false);
  const [showGimbal, setShowGimbal] = createSignal(false);
  const [showFilters, setShowFilters] = createSignal(false);
  const [liveOn, setLiveOn] = createSignal(false);
  const [recordingOn, setRecordingOn] = createSignal(false);
  const [mutedOn, setMutedOn] = createSignal(false);
  const [debugLoggingOn, setDebugLoggingOn] = createSignal(false);
  const [zoomValue, setZoomValue] = createSignal("");
  const [zoomPresets, setZoomPresets] = createSignal<ZoomPreset[]>([]);
  const [currentZoomPresetId, setCurrentZoomPresetId] = createSignal<string | null>(null);
  const [scenes, setScenes] = createSignal<NamedItem[]>([]);
  const [currentSceneId, setCurrentSceneId] = createSignal("");
  const [autoSwitchers, setAutoSwitchers] = createSignal<NamedItem[]>([]);
  const [currentAutoSwitcherId, setCurrentAutoSwitcherId] = createSignal("");
  const [mics, setMics] = createSignal<NamedItem[]>([]);
  const [currentMicId, setCurrentMicId] = createSignal("");
  const [bitratePresets, setBitratePresets] = createSignal<BitratePreset[]>([]);
  const [currentBitrateId, setCurrentBitrateId] = createSignal("");
  const [srtEnabled, setSrtEnabled] = createSignal(false);
  const [srtPriorities, setSrtPriorities] = createStore<SrtPriority[]>([]);
  const [gimbalPresets, setGimbalPresets] = createSignal<GimbalPreset[]>([]);
  const [filterStates, setFilterStates] = createStore<Record<string, boolean>>({});
  let logContainer: HTMLDivElement | undefined;

  class IndexConnection extends WebSocketConnection {
    statusTimerId: ReturnType<typeof setTimeout> | undefined;
    settingsTimerId: ReturnType<typeof setTimeout> | undefined;

    constructor() {
      super();
      this.statusTimerId = undefined;
      this.settingsTimerId = undefined;
    }

    onStatusChanged(newStatus: string): void {
      setStatus(newStatus);
    }

    onConnected(): void {
      this.sendStartStatusRequest();
      this.sendGetStatusRequest();
      this.sendGetSettingsRequest();
    }

    reconnectSoon(): void {
      if (this.statusTimerId !== undefined) {
        clearTimeout(this.statusTimerId);
        this.statusTimerId = undefined;
      }
      if (this.settingsTimerId !== undefined) {
        clearTimeout(this.settingsTimerId);
        this.settingsTimerId = undefined;
      }
      super.reconnectSoon();
    }

    handleResponse(_id: number, result: { ok: boolean }, data?: ResponseData): void {
      if (!result.ok || data === undefined) return;
      if (data.getStatus !== undefined) {
        this.handleGetStatusResponse(data.getStatus);
      } else if (data.getSettings !== undefined) {
        this.handleGetSettingsResponse(data.getSettings);
      }
    }

    handleGetStatusResponse(status: Record<string, unknown>): void {
      updateStatus(status);
      this.statusTimerId = setTimeout(() => {
        this.sendGetStatusRequest();
      }, 1000);
    }

    handleGetSettingsResponse(settingsData: { data: Record<string, unknown> }): void {
      populateSettings(settingsData.data);
      this.settingsTimerId = setTimeout(() => {
        this.sendGetSettingsRequest();
      }, 10000);
    }

    handleEvent(data: EventData): void {
      if (data.state !== undefined) {
        this.handleStateEvent(data.state);
      } else if (data.log !== undefined) {
        const entry = document.createElement("div");
        entry.textContent = data.log.entry;
        if (logContainer) logContainer.appendChild(entry);
      }
    }

    handleStateEvent(state: { data: Record<string, unknown> }): void {
      const sd = state.data;
      if (sd.streaming !== undefined) setLiveOn(sd.streaming as boolean);
      if (sd.recording !== undefined) setRecordingOn(sd.recording as boolean);
      if (sd.muted !== undefined) setMutedOn(sd.muted as boolean);
      if (sd.debugLogging !== undefined) setDebugLoggingOn(sd.debugLogging as boolean);
      if (sd.zoom !== undefined) setZoomValue(String(sd.zoom));
      if (sd.scene !== undefined) {
        setCurrentSceneId(sd.scene as string);
      }
      if (sd.mic !== undefined) {
        setCurrentMicId(sd.mic as string);
      }
      if (sd.bitrate !== undefined) {
        setCurrentBitrateId(sd.bitrate as string);
      }
      if (sd.zoomPreset !== undefined) {
        setCurrentZoomPresetId(sd.zoomPreset as string);
      }
      if (sd.zoomPresets !== undefined) {
        setZoomPresets(sd.zoomPresets as ZoomPreset[]);
        setCurrentZoomPresetId((sd.zoomPreset as string | undefined) ?? null);
      }
      if (sd.autoSceneSwitcher !== undefined) {
        const switcher = sd.autoSceneSwitcher as { id: string } | null;
        setCurrentAutoSwitcherId(switcher ? (switcher.id ?? "") : "");
      }
      if (sd.filters !== undefined) {
        const filters = sd.filters as unknown[];
        for (let filterIndex = 0; filterIndex < filters.length; filterIndex += 2) {
          const name = Object.keys(filters[filterIndex] as object)[0];
          const on = filters[filterIndex + 1] as boolean;
          setFilterStates(name, on);
        }
      }
    }
  }

  const connection = new IndexConnection();

  function overlayStatusRows(overlay: Record<string, { message: string }>): StatusRow[] {
    return Object.keys(overlay)
      .sort()
      .filter((key) => statusKeyToName[key as keyof typeof statusKeyToName])
      .map((key) => [statusKeyToName[key as keyof typeof statusKeyToName], overlay[key].message]);
  }

  function updateStatus(status: Record<string, unknown>): void {
    const general = status.general as {
      batteryLevel: number;
      isMuted: boolean;
      flame: string;
      wiFiSsid: string;
    };
    const genRows: StatusRow[] = [
      ["Battery level", String(general.batteryLevel)],
      ["Muted", String(general.isMuted)],
      ["Flame", general.flame],
      ["WiFi", general.wiFiSsid],
    ];
    setGeneralRows(genRows);
    const topLeft = (status.topLeft ?? {}) as Record<string, { message: string }>;
    setTopLeftRows(overlayStatusRows(topLeft));
    const topRight = (status.topRight ?? {}) as Record<string, { message: string }>;
    setTopRightRows(overlayStatusRows(topRight));
  }

  function populateSettings(data: Record<string, unknown>): void {
    setShowControl(true);
    setScenes((data.scenes as NamedItem[]) ?? []);
    let baseAutoSceneSwitchers: NamedItem[] = [{ id: "", name: "-- None --" }];
    setAutoSwitchers(baseAutoSceneSwitchers.concat(data.autoSceneSwitchers as NamedItem[]) ?? []);
    setMics((data.mics as NamedItem[]) ?? []);
    setBitratePresets((data.bitratePresets as BitratePreset[]) ?? []);
    const srt = data.srt as
      | {
          connectionPriorities: SrtPriority[];
          connectionPrioritiesEnabled: boolean;
        }
      | undefined;
    if (srt && srt.connectionPriorities && srt.connectionPriorities.length > 0) {
      setShowSrt(true);
      setSrtEnabled(srt.connectionPrioritiesEnabled);
      setSrtPriorities(srt.connectionPriorities);
    }
    const gimbalPresetList = data.gimbalPresets as GimbalPreset[] | undefined;
    if (gimbalPresetList && gimbalPresetList.length > 0) {
      setShowGimbal(true);
      setGimbalPresets(gimbalPresetList);
    }
    setShowFilters(true);
  }

  function handleZoomSubmit() {
    const value = parseFloat(zoomValue());
    if (!isNaN(value)) connection.setZoom(value);
  }

  function Links() {
    return (
      <div class="text-center space-x-4">
        <a href="./remote.html" class="text-indigo-400 hover:text-indigo-300 text-sm">
          Scoreboard Control
        </a>
        <a href="./scoreboard.html" class="text-indigo-400 hover:text-indigo-300 text-sm">
          Scoreboard Display
        </a>
        <a href="./golf.html" class="text-indigo-400 hover:text-indigo-300 text-sm">
          Golf Scoreboard
        </a>
        <a href="./recordings.html" class="text-indigo-400 hover:text-indigo-300 text-sm">
          Recordings
        </a>
        <GitHubLink />
      </div>
    );
  }

  function Status() {
    return (
      <Section title="Status">
        <h3 class="text-base font-medium text-zinc-300 mb-1">General</h3>
        <StatusTable rows={generalRows} />
        <h3 class="text-base font-medium text-zinc-300 mt-3 mb-1">Top left</h3>
        <StatusTable rows={topLeftRows} />
        <h3 class="text-base font-medium text-zinc-300 mt-3 mb-1">Top right</h3>
        <StatusTable rows={topRightRows} />
      </Section>
    );
  }

  function Control() {
    return (
      <Section title="Control">
        <Show when={showControl()}>
          <div class="space-y-3">
            <Toggle
              id="controlLive"
              checked={liveOn()}
              onChange={(event) => connection.setLive(event.target.checked)}
              label="Live"
            />
            <Toggle
              id="controlRecording"
              checked={recordingOn()}
              onChange={(event) => connection.setRecording(event.target.checked)}
              label="Recording"
            />
            <Toggle
              id="controlMuted"
              checked={mutedOn()}
              onChange={(event) => connection.setMuted(event.target.checked)}
              label="Muted"
            />
            <div class="flex items-center space-x-4">
              <label class="text-sm text-zinc-200 w-24 shrink-0">Zoom</label>
              <input
                type="text"
                class="bg-zinc-800 border border-zinc-600 rounded px-2 py-1 text-sm text-zinc-200 w-20"
                placeholder="1.0"
                value={zoomValue()}
                onInput={(event) => setZoomValue(event.target.value)}
                onKeyDown={(event) => {
                  if (event.key === "Enter") handleZoomSubmit();
                }}
                onBlur={handleZoomSubmit}
              />
            </div>
            <Show when={zoomPresets().length > 0}>
              <div class="flex flex-wrap gap-2">
                <For each={zoomPresets()}>
                  {(preset) => (
                    <Button
                      class={
                        preset.id === currentZoomPresetId()
                          ? "bg-indigo-700 text-white"
                          : "bg-zinc-700 hover:bg-zinc-600 text-zinc-200"
                      }
                      onClick={() => connection.setZoomPreset(preset.id)}
                    >
                      {preset.name}
                    </Button>
                  )}
                </For>
              </div>
            </Show>
            <Picker
              name="Scene"
              options={scenes}
              value={currentSceneId}
              onChange={(value) => connection.setScene(value)}
            />
            <Picker
              name="Auto scene switcher"
              options={autoSwitchers}
              value={currentAutoSwitcherId}
              onChange={(value) => {
                connection.setAutoSceneSwitcher(value === "" ? null : value);
              }}
            />
            <Picker
              name="Mic"
              options={mics}
              value={currentMicId}
              onChange={(value) => connection.setMic(value)}
            />
            <Picker
              name="Bitrate"
              options={(): NamedItem[] => {
                return bitratePresets().map(({ id, bitrate }): NamedItem => {
                  return { id, name: bitrate > 0 ? formatBytesPerSecond(bitrate) : "Unknown" };
                });
              }}
              value={currentBitrateId}
              onChange={(value) => connection.setBitratePreset(value)}
            />
            <Toggle
              id="controlDebugLogging"
              checked={debugLoggingOn()}
              onChange={(event) => connection.setDebugLogging(event.target.checked)}
              label="Debug logging"
            />
            <div class="flex flex-wrap gap-2">
              <Button
                class="bg-zinc-700 hover:bg-zinc-600 text-zinc-200"
                onClick={() => connection.reloadBrowserWidgets()}
              >
                Reload browser widgets
              </Button>
            </div>
          </div>
        </Show>
      </Section>
    );
  }

  function SrtConnectionPriorities() {
    return (
      <Show when={showSrt()}>
        <Section title="SRT Connection Priorities">
          <Toggle
            id="controlSrtEnabled"
            checked={srtEnabled()}
            onChange={(event) => {
              setSrtEnabled(event.target.checked);
              connection.setSrtConnectionPrioritiesEnabled(event.target.checked);
            }}
            label="Enabled"
          />
          <div class="space-y-2 mt-3">
            <For each={srtPriorities}>
              {(priority, priorityIndex) => (
                <SrtPriorityRow
                  priority={priority}
                  onChange={(priorityValue, enabled) => {
                    setSrtPriorities(priorityIndex(), "priority", priorityValue);
                    setSrtPriorities(priorityIndex(), "enabled", enabled);
                    connection.setSrtConnectionPriority(priority.id, priorityValue, enabled);
                  }}
                />
              )}
            </For>
          </div>
        </Section>
      </Show>
    );
  }

  function GimbalPresets() {
    return (
      <Show when={showGimbal()}>
        <Section title="Gimbal Presets">
          <div class="flex flex-wrap gap-2">
            <For each={gimbalPresets()}>
              {(preset) => (
                <Button
                  class="bg-zinc-700 hover:bg-zinc-600 text-zinc-200 px-4 py-2"
                  onClick={() => connection.moveToGimbalPreset(preset.id)}
                >
                  {preset.name}
                </Button>
              )}
            </For>
          </div>
        </Section>
      </Show>
    );
  }

  function Filters() {
    return (
      <Show when={showFilters()}>
        <Section title="Filters">
          <div class="space-y-3">
            <For each={allFilterKeys}>
              {(key) => (
                <Toggle
                  id={`filter_${key}`}
                  checked={filterStates[key] || false}
                  onChange={(event) => {
                    setFilterStates(key, event.target.checked);
                    connection.setFilter(key, event.target.checked);
                  }}
                  label={filterNames[key as keyof typeof filterNames] || key}
                />
              )}
            </For>
          </div>
        </Section>
      </Show>
    );
  }

  function Log() {
    return (
      <Section title="Log">
        <div
          ref={(el: HTMLDivElement) => {
            logContainer = el;
          }}
          class="overflow-y-auto h-96 text-sm text-zinc-300"
        />
      </Section>
    );
  }

  return (
    <div class="max-w-3xl mx-auto space-y-2">
      <Title title="Moblin Remote Control" />
      <Links />
      <ConnectingOverlay status={status} />
      <Status />
      <Control />
      <SrtConnectionPriorities />
      <GimbalPresets />
      <Filters />
      <Log />
    </div>
  );
}

interface SrtPriorityRowProps {
  priority: SrtPriority;
  onChange: (priority: number, enabled: boolean) => void;
}

function SrtPriorityRow({ priority, onChange }: SrtPriorityRowProps) {
  const [sliderValue, setSliderValue] = createSignal(priority.priority);
  const [checked, setChecked] = createSignal(priority.enabled);

  return (
    <div class="flex items-center space-x-3">
      <label class="text-sm text-zinc-200 w-24 shrink-0">{priority.name}</label>
      <input
        type="checkbox"
        checked={checked()}
        class="w-4 h-4 bg-zinc-800 border border-zinc-600 rounded cursor-pointer accent-indigo-600"
        onChange={(event) => {
          setChecked(event.target.checked);
          onChange(sliderValue(), event.target.checked);
        }}
      />
      <input
        type="range"
        min="1"
        max="10"
        value={sliderValue()}
        class="flex-1 accent-indigo-600"
        onInput={(event) => setSliderValue(parseInt(event.target.value))}
        onChange={(event) => onChange(parseInt(event.target.value), checked())}
      />
      <span class="text-sm text-zinc-300 w-6 text-right">{sliderValue()}</span>
    </div>
  );
}

render(() => <App />, document.getElementById("app")!);

// WebSrc/src/Index.svelte
<svelte:head>
  <title>Moblin Remote Control</title>
  <link rel="icon" type="image/x-icon" href="favicon.ico" />
  <link rel="stylesheet" href="css/app.css" />
</svelte:head>

<script>
  import { WebSocketConnection, connectionStatus } from "./lib/websocket.js";

  const filterNames = {
    pixellate: "Pixellate",
    movie: "Movie",
    grayScale: "Gray scale",
    sepia: "Sepia",
    triple: "Triple",
    twin: "Twin",
    fourThree: "4:3",
    crt: "CRT",
    pinch: "Pinch",
    whirlpool: "Whirlpool",
    poll: "Poll",
    blurFaces: "Blur faces",
    privacy: "Blur background",
    beauty: "Beauty",
    moblinInMouth: "Moblin in mouth",
    cameraMan: "Camera man",
  };

  const allFilterKeys = [
    "pixellate",
    "movie",
    "grayScale",
    "sepia",
    "triple",
    "twin",
    "fourThree",
    "crt",
    "pinch",
    "whirlpool",
    "poll",
    "blurFaces",
    "privacy",
    "beauty",
    "moblinInMouth",
    "cameraMan",
  ];

  const statusKeyToName = {
    camera: "Camera",
    chat: "Chat",
    mic: "Mic",
    stream: "Stream",
    zoom: "Zoom",
    obs: "OBS",
    events: "Events",
    viewers: "Viewers",
    audioLevel: "Audio",
    location: "Location",
    moblink: "Moblink",
    remoteControl: "Remote control",
    rtmpServer: "RTMP/SRT(LA) servers",
    gameController: "Game controller",
    bitrate: "Bitrate",
    uptime: "Uptime",
    srtla: "Bonding",
    srtlaRtts: "Bonding RTT:s",
    recording: "Recording",
    browserWidgets: "Browser widgets",
    djiDevices: "DJI devices",
  };

  function formatBytesPerSecond(bps) {
    if (bps >= 1000000) return (bps / 1000000).toFixed(1) + " Mbps";
    if (bps >= 1000) return (bps / 1000).toFixed(0) + " Kbps";
    return bps + " bps";
  }

  // --- Reactive state ---
  let connStatus = $state(connectionStatus.connecting);
  let statusGeneral = $state([]);
  let statusTopLeft = $state([]);
  let statusTopRight = $state([]);
  let controlsVisible = $state(false);
  let scenes = $state([]);
  let autoSceneSwitchers = $state([]);
  let mics = $state([]);
  let bitratePresets = $state([]);
  let isLive = $state(false);
  let isRecording = $state(false);
  let isMuted = $state(false);
  let isDebugLogging = $state(false);
  let zoom = $state("");
  let selectedSceneId = $state("");
  let selectedAutoSceneSwitcherId = $state("");
  let selectedMicId = $state("");
  let selectedBitrateId = $state("");
  let zoomPresets = $state([]);
  let selectedZoomPresetId = $state(null);
  let srtVisible = $state(false);
  let srtEnabled = $state(false);
  let srtPriorities = $state([]);
  let gimbalVisible = $state(false);
  let gimbalPresets = $state([]);
  let filtersVisible = $state(false);
  let filterStates = $state({});
  let logEntries = $state([]);

  function updateStatus(s) {
    const g = s.general;
    statusGeneral = [
      { name: "Battery level", value: g.batteryLevel },
      { name: "Muted", value: g.isMuted },
      { name: "Flame", value: g.flame },
      { name: "WiFi", value: g.wiFiSsid },
    ];
    statusTopLeft = buildStatuses(s.topLeft);
    statusTopRight = buildStatuses(s.topRight);
  }

  function buildStatuses(statuses) {
    return Object.keys(statuses)
      .sort()
      .filter((k) => statusKeyToName[k])
      .map((k) => ({ name: statusKeyToName[k], value: statuses[k].message }));
  }

  function populateSettings(data) {
    controlsVisible = true;
    scenes = data.scenes || [];
    autoSceneSwitchers = data.autoSceneSwitchers || [];
    mics = data.mics || [];
    bitratePresets = (data.bitratePresets || []).map((p) => ({
      ...p,
      label: p.bitrate > 0 ? formatBytesPerSecond(p.bitrate) : "Unknown",
    }));
    if (data.srt && data.srt.connectionPriorities && data.srt.connectionPriorities.length > 0) {
      srtVisible = true;
      srtEnabled = data.srt.connectionPrioritiesEnabled;
      srtPriorities = data.srt.connectionPriorities.map((p) => ({ ...p }));
    }
    if (data.gimbalPresets && data.gimbalPresets.length > 0) {
      gimbalVisible = true;
      gimbalPresets = data.gimbalPresets;
    }
    filtersVisible = true;
  }

  function updateFilterStates(filters) {
    const next = { ...filterStates };
    for (let i = 0; i < filters.length; i += 2) {
      const name = Object.keys(filters[i])[0];
      next[name] = filters[i + 1];
    }
    filterStates = next;
  }

  // --- WebSocket connection ---
  class Connection extends WebSocketConnection {
    constructor() {
      super();
      this.statusTimerId = undefined;
    }

    onStatusChanged(s) {
      connStatus = s;
    }

    onConnected() {
      this.sendStartStatusRequest();
      this.sendGetStatusRequest();
      this.sendGetSettingsRequest();
    }

    reconnectSoon() {
      if (this.statusTimerId != undefined) {
        clearTimeout(this.statusTimerId);
        this.statusTimerId = undefined;
      }
      super.reconnectSoon();
    }

    handleResponse(_id, result, data) {
      if (!result.ok) {
        console.log("Unsuccessful request: ", result);
        return;
      }
      if (!data) return;
      if (data.getStatus) {
        updateStatus(data.getStatus);
        this.statusTimerId = setTimeout(() => this.sendGetStatusRequest(), 1000);
      }
      if (data.getSettings) populateSettings(data.getSettings.data);
    }

    handleEvent(data) {
      if (data.state) {
        const d = data.state.data;
        if (d.streaming !== undefined) isLive = d.streaming;
        if (d.recording !== undefined) isRecording = d.recording;
        if (d.muted !== undefined) isMuted = d.muted;
        if (d.debugLogging !== undefined) isDebugLogging = d.debugLogging;
        if (d.zoom !== undefined) zoom = d.zoom;
        if (d.scene !== undefined) selectedSceneId = d.scene;
        if (d.mic !== undefined) selectedMicId = d.mic;
        if (d.bitrate !== undefined) selectedBitrateId = d.bitrate;
        if (d.zoomPreset !== undefined) selectedZoomPresetId = d.zoomPreset;
        if (d.zoomPresets !== undefined) zoomPresets = d.zoomPresets;
        if (d.autoSceneSwitcher !== undefined) {
          selectedAutoSceneSwitcherId = d.autoSceneSwitcher ? d.autoSceneSwitcher.id : "";
        }
        if (d.filters !== undefined) updateFilterStates(d.filters);
      } else if (data.log) {
        logEntries = [...logEntries, data.log.entry];
      }
    }
  }

  const connection = new Connection();

  function submitZoom() {
    const val = parseFloat(zoom);
    if (!isNaN(val)) connection.setZoom(val);
  }

  function handleSrtSliderInput(e, priority) {
    // Update local display only
    srtPriorities = srtPriorities.map((p) =>
      p.id === priority.id ? { ...p, _displayPriority: parseInt(e.target.value) } : p,
    );
  }

  function handleSrtSliderChange(e, priority) {
    const value = parseInt(e.target.value);
    const updated = srtPriorities.map((p) =>
      p.id === priority.id ? { ...p, priority: value, _displayPriority: value } : p,
    );
    srtPriorities = updated;
    const p = updated.find((p) => p.id === priority.id);
    connection.setSrtConnectionPriority(priority.id, value, p.enabled);
  }

  function handleSrtCheckboxChange(e, priority) {
    const enabled = e.target.checked;
    srtPriorities = srtPriorities.map((p) =>
      p.id === priority.id ? { ...p, enabled } : p,
    );
    connection.setSrtConnectionPriority(priority.id, priority.priority, enabled);
  }
</script>

<div class="bg-zinc-950 text-zinc-100 font-sans p-2">
  <div class="max-w-3xl mx-auto space-y-2">
    <h1 class="text-2xl font-bold text-center">Moblin Remote Control</h1>

    <div class="text-center space-x-4">
      <a href="./remote.html" class="text-indigo-400 hover:text-indigo-300 text-sm"
        >Scoreboard Control</a
      >
      <a href="./scoreboard.html" class="text-indigo-400 hover:text-indigo-300 text-sm"
        >Scoreboard Display</a
      >
      <a href="./golf.html" class="text-indigo-400 hover:text-indigo-300 text-sm"
        >Golf Scoreboard</a
      >
      <a href="./recordings.html" class="text-indigo-400 hover:text-indigo-300 text-sm"
        >Recordings</a
      >
      <a
        href="https://github.com/eerimoq/moblin"
        target="_blank"
        class="text-indigo-400 hover:text-indigo-300 text-sm"
      >
        Github
      </a>
    </div>

    <div class="pb-1 text-center">
      {#if connStatus === connectionStatus.connecting}
        <span class="text-sm text-yellow-400">Connecting to server</span>
      {:else if connStatus === connectionStatus.connected}
        <span class="text-sm text-green-500">Connected to server</span>
      {:else}
        <span class="text-sm text-red-500">Unknown server status</span>
      {/if}
    </div>

    <!-- Status -->
    <div class="bg-zinc-900 border border-zinc-700 rounded-lg p-2">
      <h2 class="text-xl font-semibold mb-3">Status</h2>
      <h3 class="text-base font-medium text-zinc-300 mb-1">General</h3>
      <div class="overflow-x-auto">
        <table class="w-full text-sm text-left text-zinc-300 table-auto">
          <tbody>
            {#each statusGeneral as row}
              <tr class="border-b border-zinc-800">
                <td class="py-1.5 pr-4 text-zinc-200 font-medium whitespace-nowrap">{row.name}</td>
                <td class="py-1.5 text-zinc-200">{row.value}</td>
              </tr>
            {/each}
          </tbody>
        </table>
      </div>
      <h3 class="text-base font-medium text-zinc-300 mt-3 mb-1">Top left</h3>
      <div class="overflow-x-auto">
        <table class="w-full text-sm text-left text-zinc-300 table-auto">
          <tbody>
            {#each statusTopLeft as row}
              <tr class="border-b border-zinc-800">
                <td class="py-1.5 pr-4 text-zinc-200 font-medium whitespace-nowrap">{row.name}</td>
                <td class="py-1.5 text-zinc-200">{row.value}</td>
              </tr>
            {/each}
          </tbody>
        </table>
      </div>
      <h3 class="text-base font-medium text-zinc-300 mt-3 mb-1">Top right</h3>
      <div class="overflow-x-auto">
        <table class="w-full text-sm text-left text-zinc-300 table-auto">
          <tbody>
            {#each statusTopRight as row}
              <tr class="border-b border-zinc-800">
                <td class="py-1.5 pr-4 text-zinc-200 font-medium whitespace-nowrap">{row.name}</td>
                <td class="py-1.5 text-zinc-200">{row.value}</td>
              </tr>
            {/each}
          </tbody>
        </table>
      </div>
    </div>

    <!-- Control -->
    <div class="bg-zinc-900 border border-zinc-700 rounded-lg p-2">
      <h2 class="text-xl font-semibold mb-3">Control</h2>
      {#if controlsVisible}
        <div class="space-y-3">
          <!-- Live -->
          <label class="flex items-center cursor-pointer">
            <div class="relative flex items-center">
              <input
                type="checkbox"
                class="peer appearance-none w-11 h-5 bg-slate-400 rounded-full checked:bg-indigo-800 cursor-pointer transition-colors duration-300"
                role="switch"
                checked={isLive}
                onchange={(e) => {
                  isLive = e.target.checked;
                  connection.setLive(e.target.checked);
                }}
              />
              <label
                class="absolute top-0 left-0 w-5 h-5 bg-white rounded-full border border-indigo-300 shadow-sm transition-transform duration-300 peer-checked:translate-x-6 peer-checked:border-slate-800 cursor-pointer"
              ></label>
              <span class="ml-3 text-sm text-zinc-200">Live</span>
            </div>
          </label>

          <!-- Recording -->
          <label class="flex items-center cursor-pointer">
            <div class="relative flex items-center">
              <input
                type="checkbox"
                class="peer appearance-none w-11 h-5 bg-slate-400 rounded-full checked:bg-indigo-800 cursor-pointer transition-colors duration-300"
                role="switch"
                checked={isRecording}
                onchange={(e) => {
                  isRecording = e.target.checked;
                  connection.setRecording(e.target.checked);
                }}
              />
              <label
                class="absolute top-0 left-0 w-5 h-5 bg-white rounded-full border border-indigo-300 shadow-sm transition-transform duration-300 peer-checked:translate-x-6 peer-checked:border-slate-800 cursor-pointer"
              ></label>
              <span class="ml-3 text-sm text-zinc-200">Recording</span>
            </div>
          </label>

          <!-- Muted -->
          <label class="flex items-center cursor-pointer">
            <div class="relative flex items-center">
              <input
                type="checkbox"
                class="peer appearance-none w-11 h-5 bg-slate-400 rounded-full checked:bg-indigo-800 cursor-pointer transition-colors duration-300"
                role="switch"
                checked={isMuted}
                onchange={(e) => {
                  isMuted = e.target.checked;
                  connection.setMuted(e.target.checked);
                }}
              />
              <label
                class="absolute top-0 left-0 w-5 h-5 bg-white rounded-full border border-indigo-300 shadow-sm transition-transform duration-300 peer-checked:translate-x-6 peer-checked:border-slate-800 cursor-pointer"
              ></label>
              <span class="ml-3 text-sm text-zinc-200">Muted</span>
            </div>
          </label>

          <!-- Zoom -->
          <div class="flex items-center space-x-4">
            <label class="text-sm text-zinc-200 w-24 shrink-0">Zoom</label>
            <input
              type="text"
              class="bg-zinc-800 border border-zinc-600 rounded px-2 py-1 text-sm text-zinc-200 w-20"
              placeholder="1.0"
              value={zoom}
              oninput={(e) => (zoom = e.target.value)}
              onkeydown={(e) => {
                if (e.key === "Enter") submitZoom();
              }}
              onblur={submitZoom}
            />
          </div>

          <!-- Zoom presets -->
          {#if zoomPresets.length > 0}
            <div class="flex flex-wrap gap-2">
              {#each zoomPresets as preset (preset.id)}
                <button
                  class={preset.id === selectedZoomPresetId
                    ? "bg-indigo-700 text-white text-sm px-3 py-1 rounded transition-colors"
                    : "bg-zinc-700 hover:bg-zinc-600 text-zinc-200 text-sm px-3 py-1 rounded transition-colors"}
                  onclick={() => {
                    selectedZoomPresetId = preset.id;
                    connection.setZoomPreset(preset.id);
                  }}
                >
                  {preset.name}
                </button>
              {/each}
            </div>
          {/if}

          <!-- Scene -->
          <div class="flex items-center space-x-4">
            <label class="text-sm text-zinc-200 w-24 shrink-0">Scene</label>
            <select
              class="bg-zinc-800 border border-zinc-600 rounded px-2 py-1 text-sm text-zinc-200 flex-1"
              value={selectedSceneId}
              onchange={(e) => {
                selectedSceneId = e.target.value;
                connection.setScene(e.target.value);
              }}
            >
              {#each scenes as scene (scene.id)}
                <option value={scene.id}>{scene.name}</option>
              {/each}
            </select>
          </div>

          <!-- Auto scene switcher -->
          <div class="flex items-center space-x-4">
            <label class="text-sm text-zinc-200 w-24 shrink-0">Auto scene</label>
            <select
              class="bg-zinc-800 border border-zinc-600 rounded px-2 py-1 text-sm text-zinc-200 flex-1"
              value={selectedAutoSceneSwitcherId}
              onchange={(e) => {
                selectedAutoSceneSwitcherId = e.target.value;
                connection.setAutoSceneSwitcher(e.target.value === "" ? null : e.target.value);
              }}
            >
              <option value="">-- None --</option>
              {#each autoSceneSwitchers as switcher (switcher.id)}
                <option value={switcher.id}>{switcher.name}</option>
              {/each}
            </select>
          </div>

          <!-- Mic -->
          <div class="flex items-center space-x-4">
            <label class="text-sm text-zinc-200 w-24 shrink-0">Mic</label>
            <select
              class="bg-zinc-800 border border-zinc-600 rounded px-2 py-1 text-sm text-zinc-200 flex-1"
              value={selectedMicId}
              onchange={(e) => {
                selectedMicId = e.target.value;
                connection.setMic(e.target.value);
              }}
            >
              {#each mics as mic (mic.id)}
                <option value={mic.id}>{mic.name}</option>
              {/each}
            </select>
          </div>

          <!-- Bitrate -->
          <div class="flex items-center space-x-4">
            <label class="text-sm text-zinc-200 w-24 shrink-0">Bitrate</label>
            <select
              class="bg-zinc-800 border border-zinc-600 rounded px-2 py-1 text-sm text-zinc-200 flex-1"
              value={selectedBitrateId}
              onchange={(e) => {
                selectedBitrateId = e.target.value;
                connection.setBitratePreset(e.target.value);
              }}
            >
              {#each bitratePresets as preset (preset.id)}
                <option value={preset.id}>{preset.label}</option>
              {/each}
            </select>
          </div>

          <!-- Debug logging -->
          <label class="flex items-center cursor-pointer">
            <div class="relative flex items-center">
              <input
                type="checkbox"
                class="peer appearance-none w-11 h-5 bg-slate-400 rounded-full checked:bg-indigo-800 cursor-pointer transition-colors duration-300"
                role="switch"
                checked={isDebugLogging}
                onchange={(e) => {
                  isDebugLogging = e.target.checked;
                  connection.setDebugLogging(e.target.checked);
                }}
              />
              <label
                class="absolute top-0 left-0 w-5 h-5 bg-white rounded-full border border-indigo-300 shadow-sm transition-transform duration-300 peer-checked:translate-x-6 peer-checked:border-slate-800 cursor-pointer"
              ></label>
              <span class="ml-3 text-sm text-zinc-200">Debug logging</span>
            </div>
          </label>

          <div class="flex flex-wrap gap-2">
            <button
              class="bg-zinc-700 hover:bg-zinc-600 text-zinc-200 text-sm px-3 py-1 rounded transition-colors"
              onclick={() => connection.reloadBrowserWidgets()}
            >
              Reload browser widgets
            </button>
          </div>
        </div>
      {/if}
    </div>

    <!-- SRT Connection Priorities -->
    {#if srtVisible}
      <div class="bg-zinc-900 border border-zinc-700 rounded-lg p-2">
        <h2 class="text-xl font-semibold mb-3">SRT Connection Priorities</h2>
        <label class="flex items-center cursor-pointer mb-3">
          <div class="relative flex items-center">
            <input
              type="checkbox"
              class="peer appearance-none w-11 h-5 bg-slate-400 rounded-full checked:bg-indigo-800 cursor-pointer transition-colors duration-300"
              role="switch"
              checked={srtEnabled}
              onchange={(e) => {
                srtEnabled = e.target.checked;
                connection.setSrtConnectionPrioritiesEnabled(e.target.checked);
              }}
            />
            <label
              class="absolute top-0 left-0 w-5 h-5 bg-white rounded-full border border-indigo-300 shadow-sm transition-transform duration-300 peer-checked:translate-x-6 peer-checked:border-slate-800 cursor-pointer"
            ></label>
            <span class="ml-3 text-sm text-zinc-200">Enabled</span>
          </div>
        </label>
        <div class="space-y-2">
          {#each srtPriorities as priority (priority.id)}
            {@const displayPriority = priority._displayPriority ?? priority.priority}
            <div class="flex items-center space-x-3">
              <label class="text-sm text-zinc-200 w-24 shrink-0">{priority.name}</label>
              <input
                type="checkbox"
                class="w-4 h-4 bg-zinc-800 border border-zinc-600 rounded cursor-pointer accent-indigo-600"
                checked={priority.enabled}
                onchange={(e) => handleSrtCheckboxChange(e, priority)}
              />
              <input
                type="range"
                min="0"
                max="9"
                value={displayPriority}
                class="flex-1 accent-indigo-600"
                oninput={(e) => handleSrtSliderInput(e, priority)}
                onchange={(e) => handleSrtSliderChange(e, priority)}
              />
              <span class="text-sm text-zinc-300 w-6 text-right">{displayPriority}</span>
            </div>
          {/each}
        </div>
      </div>
    {/if}

    <!-- Gimbal Presets -->
    {#if gimbalVisible}
      <div class="bg-zinc-900 border border-zinc-700 rounded-lg p-2">
        <h2 class="text-xl font-semibold mb-3">Gimbal Presets</h2>
        <div class="flex flex-wrap gap-2">
          {#each gimbalPresets as preset (preset.id)}
            <button
              class="bg-zinc-700 hover:bg-zinc-600 text-zinc-200 text-sm px-4 py-2 rounded transition-colors"
              onclick={() => connection.moveToGimbalPreset(preset.id)}
            >
              {preset.name}
            </button>
          {/each}
        </div>
      </div>
    {/if}

    <!-- Filters -->
    {#if filtersVisible}
      <div class="bg-zinc-900 border border-zinc-700 rounded-lg p-2">
        <h2 class="text-xl font-semibold mb-3">Filters</h2>
        <div class="space-y-3">
          {#each allFilterKeys as key}
            <label class="flex items-center cursor-pointer">
              <div class="relative flex items-center">
                <input
                  type="checkbox"
                  class="peer appearance-none w-11 h-5 bg-slate-400 rounded-full checked:bg-indigo-800 cursor-pointer transition-colors duration-300"
                  role="switch"
                  checked={filterStates[key] || false}
                  onchange={(e) => {
                    filterStates = { ...filterStates, [key]: e.target.checked };
                    connection.setFilter(key, e.target.checked);
                  }}
                />
                <label
                  class="absolute top-0 left-0 w-5 h-5 bg-white rounded-full border border-indigo-300 shadow-sm transition-transform duration-300 peer-checked:translate-x-6 peer-checked:border-slate-800 cursor-pointer"
                ></label>
                <span class="ml-3 text-sm text-zinc-200">{filterNames[key] || key}</span>
              </div>
            </label>
          {/each}
        </div>
      </div>
    {/if}

    <!-- Log -->
    <div class="bg-zinc-900 border border-zinc-700 rounded-lg p-2">
      <h2 class="text-xl font-semibold mb-3">Log</h2>
      <div class="overflow-y-auto h-96 text-sm text-zinc-300">
        {#each logEntries as entry}
          <div>{entry}</div>
        {/each}
      </div>
    </div>
  </div>
</div>
